mkdir -p course/fr/transcript/module1
mkdir -p course/fr/transcript/module2
mkdir -p course/fr/transcript/module3
mkdir -p course/fr/transcript/module4
mkdir -p course/fr/transcript/module5
mkdir -p course/fr/transcript/module6
mkdir -p course/fr/transcript/module7
mkdir -p course/fr/transcript/module8
mkdir -p course/fr/transcript/module9
mkdir -p course/fr/transcript/module10
mkdir -p course/fr/transcript/module11
mkdir -p course/fr/transcript/module12
mkdir -p course/fr/transcript/module13
mkdir -p course/fr/transcript/module14
mkdir -p course/fr/transcript/module15
mkdir -p course/fr/transcript/module16
rm -f course/fr/data/transcripts.zip
cp ./module3/course/fr/transcript/video.txt course/fr/transcript/module3/video.txt
cp ./module3/course/fr/transcript/fr.docx course/fr/transcript/module3/fr.docx
cp ./module12/course/fr/transcript/video.txt course/fr/transcript/module12/video.txt
cp ./module12/course/fr/transcript/fr.docx course/fr/transcript/module12/fr.docx
cp ./module11/course/fr/transcript/video.txt course/fr/transcript/module11/video.txt
cp ./module11/course/fr/transcript/fr.docx course/fr/transcript/module11/fr.docx
cp ./module8/course/fr/transcript/fr.docx course/fr/transcript/module8/fr.docx
cp ./module8/course/fr/transcript/video.txt course/fr/transcript/module8/video.txt
cp ./module10/course/fr/transcript/video.txt course/fr/transcript/module10/video.txt
cp ./module10/course/fr/transcript/fr.docx course/fr/transcript/module10/fr.docx
cp ./module13/course/fr/transcript/fr.docx course/fr/transcript/module13/fr.docx
cp ./module13/course/fr/transcript/video.txt course/fr/transcript/module13/video.txt
cp ./module1/course/fr/transcript/video.txt course/fr/transcript/module1/video.txt
cp ./module1/course/fr/transcript/fr.docx course/fr/transcript/module1/fr.docx
cp ./module7/course/fr/transcript/video.txt course/fr/transcript/module7/video.txt
cp ./module7/course/fr/transcript/fr.docx course/fr/transcript/module7/fr.docx
cp ./module15/course/fr/transcript/fr.docx course/fr/transcript/module15/fr.docx
cp ./module14/course/fr/transcript/fr.docx course/fr/transcript/module14/fr.docx
cp ./module6/course/fr/transcript/video.txt course/fr/transcript/module6/video.txt
cp ./module6/course/fr/transcript/fr.docx course/fr/transcript/module6/fr.docx
cp ./module9/course/fr/transcript/video.txt course/fr/transcript/module9/video.txt
cp ./module9/course/fr/transcript/fr.docx course/fr/transcript/module9/fr.docx
cp ./module16/course/fr/transcript/fr.docx course/fr/transcript/module16/fr.docx
cp ./module2/course/fr/transcript/video.txt course/fr/transcript/module2/video.txt
cp ./module2/course/fr/transcript/fr.docx course/fr/transcript/module2/fr.docx
cp ./module5/course/fr/transcript/video.txt course/fr/transcript/module5/video.txt
cp ./module5/course/fr/transcript/fr.docx course/fr/transcript/module5/fr.docx
cp ./module4/course/fr/transcript/video.txt course/fr/transcript/module4/video.txt
cp ./module4/course/fr/transcript/fr.docx course/fr/transcript/module4/fr.docx
cd course/fr/
zip -r data/transcripts.zip transcript
cd ../../
rm -fR course/fr/transcript
